_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: d0bc6ffd-8cc1-46b9-946d-07216d63cf4e
name: 'Princeton Research Data Service'
mail: aliauw@princeton.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/7
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
